# Generated by Django 2.2 on 2020-01-19 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('addr', models.TextField(max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Pulses'), ('SW', 'Rice'), ('OW', 'Wheat'), ('FR', 'Fruits'), ('VG', 'Vegetables')], max_length=2),
        ),
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('dos', models.DateField()),
                ('price', models.CharField(max_length=4)),
                ('quantity', models.CharField(max_length=10)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Farmer')),
            ],
        ),
    ]
